---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.cluster.local
  resources:
  - servicemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.cluster.local
  resources:
  - servicemonitors/finalizers
  verbs:
  - update
- apiGroups:
  - monitoring.cluster.local
  resources:
  - servicemonitors/status
  verbs:
  - get
  - patch
  - update
