# permissions for end users to view servicemonitors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-housekeeper
    app.kubernetes.io/managed-by: kustomize
  name: servicemonitor-viewer-role
rules:
- apiGroups:
  - monitoring.cluster.local
  resources:
  - servicemonitors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.cluster.local
  resources:
  - servicemonitors/status
  verbs:
  - get
